### ISSUE TITLE
Article Formatting Issue

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#106]
for eg. see below article
http://beta.fitrangi.com/article/trekking-in-sahyadri-region

**you will see every paragraph start with a incomplete line....although it is perfect in editing version...but not looking in one line in actual view
** also the distance between two  paragrapghs is more compared to assign distance in editing version

**Comment by arshadansari27** [comment]
@YunusDange 

The issue is with the way the data is copy pasted.. Please do not copy paste from microsoft word.. Copy the content from microsoft word to notepad (please note: only notepad and not wordpad) then paste it here.. This is only in case of copy pasting..
I checked the source code of the text in editor, you can also see when you are in editor mode there is a button in the list of buttons to the right, called source and look like this (< >).... One you click that and see too many formatting information, then know that copy paste was done from rich text editor and format got screwed while copy pasting....

**Comment by YunusDange** [comment]
got it...
but is there any solution for this?
as we are expecting users will write blogs and articles for us...so we can't tell this approach to users..the normal tendency is either they directly write in the editor or COPY - PASTE from wordfile...
so we will be having this problem for sure.. so try to find if there is any solution for this...like it works in wordpress, drupal backend which i have used

**Comment by arshadansari27** [comment]
There is only one possible solution for this... Not to give our visitors a complete word like editor.. Make it more like use existing templates and change the content inside the template... It is some work... but our content will become awesome after that...

**Comment by YunusDange** [comment]
i may need reference to understand this...like how it will work..

any live websites using this kind of thing etc.?

**Comment by YunusDange** [comment]
![screenshot 2015-05-24 08 23 14](https://cloud.githubusercontent.com/assets/7126709/7786440/2b9578d6-01ee-11e5-8585-2ac8c062d06f.png)

One thing is improve in backend that...now content is copy pasted as plain text without any formatting...but after doing a little bit a formating in editor itself once user save that.....this is the actual result he get..
