### ISSUE TITLE
Chat Message - Overall functionality Issues

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#108]
Following are the issues i find in chat functionality 

1) Whenever i right message and press enter it takes time to reflect in the message box.....it's not real time....so user will get confused

2) There is a count icon on every profile with whome we are chatting...which is to show no. of unread messages i guess...which is not working

3) Biggest Issue is.....notifications.....there is no notification system which show that there is a new message....how user will know that he receive a new chat message?

4) There is a option for Attachment (audio,video, image) but it's not working

**Comment by arshadansari27** [comment]
Here is how I will be doing this..

1) This is because we are not using messaging apis like xmpp for now.. it will require more server side processing that our server will have problem running alongside the site.. So shifting to real time can only happen when we have money to add servers.. however, i will trick the system to add the message on the box right away without having to wait for the response from server.. that will trick the user to think it is realtime...

2) This is a work in progress

3) Notifications will be like other notifications, that will say there are new messages and user will be brought to th emessage page when he clicks on it.. on top it will only show new messages (+) sign in red indicating the arrival of new messages.

4) I want to remove the functionality to send audio, video and image, since we dont have that kind of support on serverside.. it will only make sense when we move to xmpp based servers....

**Comment by YunusDange** [comment]
1) got this

2) WIP

3) Got this...lets C how it works...& what feedback we receive from users

4) got this....Ok with it...!

**Comment by arshadansari27** [comment]
I have put this up....

Mostly 1, 2 and 3 are fixed.. we need to test this.... 4 requires me to remove those icons for additional attachments... need @89abdul 's help on this one...

**Comment by YunusDange** [comment]
1)  message is not going after hitting "Enter"button i have to click that arrow option to sent it....but now it looks like real time as after clicking that arrow it shows directly into message box without waiting...but message not getting delivered with a hit of ENTER ..this issue is there

2) Not working...nothing happens here

3) in notification i can see new message indication with number......but when i go to chat area 2nd number thing not working which should show from whome i received the message etc.
Also event after going through all the profiles showing in chat area....those notifications doesn't go ..it's still there

4) Got this

**Comment by arshadansari27** [comment]
Chatting is a huge feature and I have implemented it on bare minimal scale with too many shortcuts to avoid a huge subproject at the moment... But this will be the key in increasing user activity on site.... So it is important and hence we need to bring in some fix at the moment..

Tasks to cover urgently at the moment:

1) Hit enter to send

2) Managing this count in program is becoming pain and is adding bugs.. I plan to use "new" in red instead of the number of messaging associated with each profile. Remove the new notification from under profile, as soon as it is red. This way, I won't have to worry about too much and later fix this with correct number..

3) Manage top notifications.....

The rest of the goodness can come later..

**Comment by YunusDange** [comment]
I think this part is not done yet 

2) Managing this count in program is becoming pain and is adding bugs.. I plan to use "new" in red instead of the number of messaging associated with each profile. Remove the new notification from under profile, as soon as it is red. This way, I won't have to worry about too much and later fix this with correct number..

- after going to my message area...i can't see who sends me the message....coz neither it is highlighted nor that profile come first in the list which will show that this is the recent message 

- New issue is....when user click on his notification icon....he go to his My Page...i think in that also he should go towards his stream through which user will understand that this is the area where he can see things for which he received notification (as we doesn't have a drop-down in notification tab)

**Comment by arshadansari27** [comment]
point 1 ill look into..

point 2 is mute..
his streams is seen from mypage.. where else to take him?

**Comment by YunusDange** [comment]
Like what we have done while filtering...when user select any filter value
and click "go"...the screen goes towards a result area...similarly here
also user should go towards his stream area..coz because of out big cover
image..it create little confusion for users specially new users

**Comment by arshadansari27** [comment]
Got it... and makes sense too..

**Comment by arshadansari27** [comment]
what part is critical? the notification of message or the streams showing?

**Comment by YunusDange** [comment]
Both are linked to each other

Like User should get notification about new message and when he go to that
section he should know which profile he received a message means stream
showing

**Comment by arshadansari27** [comment]
There are two notifications, 

1) Stream notification, which will take and scroll you down to your stream views..which is used to notify you about what's going on
2) Message notification, that when clicked, will take you to chat window..

They both are not linked to each other... they are two separate use case..

**Comment by YunusDange** [comment]
Yaa i know that...here i am talking about only CHAT NOTIFICATIONS..

notification of message is critical...

User should get notifications that he has a new message (notification in numbers will be good)..i think it is working properly now
but
when user go to Chat window....there is lot of confusion......like below

1) user doesn't know from which profile he receives the new message....profiles from whom user receives new message should be highlighted in some way

2) It should be first profile (showing the latest message receive by this profile)

3) When user click on that profile...the new message should be seen.....right now i can see the first message of received from that user and have to scroll to see his new ( fresh message)

this things need to perfect

**Comment by YunusDange** [comment]
2 things have solved...
1) now i can see the notification
2) when i go to messaging window...i can also see numbers on a user profile from whom i received that message 

still have 2 issues

1) i go to that profile and read the message....but when i go to the other profile...that numbers is still there....
![screenshot-2015-05-26-09 21 00](https://cloud.githubusercontent.com/assets/7126709/7804999/9ff5e3b4-0388-11e5-89dd-61ea05782d33.jpg)

means that notification is not going even after reading that message...so next time when i visit messaging window for other new message it will make me confuse as usual ...

2) The new message profile should come first...which will indicate that it is a fresh message....like below
![screenshot-2015-05-26-09 39 37](https://cloud.githubusercontent.com/assets/7126709/7805212/b45de2f4-038b-11e5-8359-cce88fd6c7da.jpg)

or else it will make difficult for users to search the new message when there are more profiles in messaging window...which is not proper.

SO THIS 2 ISSUE NEEDS TO BE SOLVED....then it will become perfect

**Comment by arshadansari27** [comment]
create two tickets for thise two tasks.. in closing this one... there is too many changes ynder this ticket..
