### ISSUE TITLE
Finder - "Search" Filter not working

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#150]
There is a search bar below the cover image "Search by Name" 
it's not working

**Comment by arshadansari27** [comment]
did u try searching by hitting enter? there's a button to its right which is invisible... if u take mouse over it you'll see.. the problem is that some change by @89abdul  has caused it to go invisible.. i'm working on it.. for now making it blue...

if we need enter for searching, let's make a new ticket for later

**Comment by YunusDange** [comment]
I think it will be more user friendly if we have option to hit ENTER for searching for all the search box

**Comment by arshadansari27** [comment]
i cant do thay for most of the search box... coz im dependimg too much on
button to use other filters in the vicinity

**Comment by YunusDange** [comment]
Okkz...got this
