### ISSUE TITLE
Facebook Comments Plugin

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#47]
@arshadansari27 
- We should ad Facebook comment option along with website comment as most of our audience is on facebook and it is one of the best way to market the content and get more traction

- Our earlier version of fitrangi.com had this option and it proves to be very successful....gives us more visibility...

- Also , Is it possible to get those earlier comments back ? (it will show the traction to Advertisers as well as Investors for a time being)

**Comment by arshadansari27** [comment]
Either Facebook / Other similarly universal external comment service like disquss or our own. Can't have both. Simply because we cannot have multiple comments systems where it will not be easy for communication to happen. I really believe we should not be so focussed on facebook, just because lot of traffic is being generated from there. If we tie too much with facebook, then there is no point of having google login and even our own login. The more we use facebook specific services, the  more we are tied to their business plans. 

Whatever the benefits is in visibility, is far out weighted by their change of plans of using apis and development work to keep up with their changes and tying in too much to their  user base. 

Let's discuss on this first and then we can think of solution strategy.

**Comment by arshadansari27** [comment]
Im closing it for now, we can reopen post discussion? this will help keep focus on what to do...
