### ISSUE TITLE
Journal - Top Blogs TAB FUNCTIONALITY 

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#86]
right now this TAB is showing all the Blogs uploaded to the site.....same like the HOME tab of Journal ..BUT technically this section should show TOP blogs....
like Most Commented OR Most Viewed OR Admin Managed blog post.......there should be some functionality working for this TAB...

**Comment by arshadansari27** [comment]
True.. but we don't have any kind of interaction to suggest that parameter, if the blog is currently top or not.. So instead of keeping it empty, its showing all.. It will take a bit of time till people will interact with the blogs and then we can use that data to decide which are top blog. So I think we can keep it as it is for a while.... and come back to it when more users are arriving.. what say?

**Comment by YunusDange** [comment]
Cool...Sure!
